//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ace_Advertising_Screens_Admin.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public string Venue { get; set; }
        public string Content_Type { get; set; }
        public string URL { get; set; }
        public string Company { get; set; }
        public Nullable<double> Duration { get; set; }
        public int ID { get; set; }
    }
}
